### ISSUE TITLE
距離のヒストグラム

### ISSUE THREAD

**Issue by MistletoeNaoko** [MistletoeNaoko/TimeTubesWeb#11]
類似検索におけるクエリとデータの距離の分布をヒストグラムで表示し、
そのヒストグラムから表示する結果の数を選択できるようにする。

**Comment by MistletoeNaoko** [comment]
@makotouemura
d8b9eb7258ff4fc1ce764f12224eb2a3cf026698
で追加しました。タイムラインの上部に以下のような形で表示されます。
<img width="984" alt="スクリーンショット 2020-02-11 午後6 15 09" src="https://user-images.githubusercontent.com/47652262/74288479-795e9c80-4cfa-11ea-9308-c4673574db9a.png">
ヒストグラム上の緑の線をドラッグ&ドロップすることで、表示する結果の数を変更することができます。

**Comment by makotouemura** [comment]
確認しました。これはすごく便利です。例として挙げてもらった分布は比較的滑らかな分布ですが、たまにある程度以上「距離」が大きくなると急に数が増えるような分布になることもあり、そういうのが見えると判断しやすいです。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
判断の手助けになったようで、よかったです。
ご報告ありがとうございます。
