### ISSUE TITLE
query-by-sketchにPA,PDを導入

### ISSUE THREAD

**Issue by MistletoeNaoko** [MistletoeNaoko/TimeTubesWeb#12]
QBSにおいてスケッチの幅などにPA、PDを割り当てたい

**Comment by MistletoeNaoko** [comment]
@makotouemura
d8b9eb7258ff4fc1ce764f12224eb2a3cf026698
にて追加されました。
QBEで幅やx軸y軸にPAやPDを割り当てることができます。
これにより、以前ご紹介いただいた、光度の上昇に伴うPDの減少（増加）をlight curve上でも表現可能になりました。
また、メインの可視化画面においても、散布図でPA、PDを選択できるようになりました。

**Comment by makotouemura** [comment]
確認しました。横軸JD、縦軸PDで、太さをFlxにして使ってみました。これまでQUでやっていた結果とほぼ一致する結果がでてます。ただ、横軸JDにすると短い時間スケールの現象をスケッチしにくい一方で、Normalizeされるから関係無いだろうと思っているのですが、結果は長めの時間スケールのサンプルが距離が小さくなって選ばれやすい気がします。スケッチは長めの時間スケールでスケッチして、捜索範囲を短めの時間に設定すればこの問題は一応解決されるのですが、時間方向の normalize が有効に働いてるのか気になりました。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
試してくださってありがとうございます。
時間軸JDの際のスケッチのしにくさは次のバージョンでは改善される予定です。
近日中に公開できると思います。

また、時間方向に正規化されるかどうかについてなのですが、
normalizeオプションを選択しても時間方向に正規化はされません（クエリとデータ内の部分時区間の長さを揃えるような処理はしていません）。
基本的にDTWでは時系列が非線形に伸縮されるので、時間方向の正規化はする必要がないのですが、Warping window sizeに値を指定すると状況が変わります。
この値を設定すると時系列の伸縮に制限がかかります。
ですので、クエリと検索したい時系列の長さが大きく違う場合にWarping window sizeを小さい値に設定すると、うまくマッチしなくなってしまうことがあると思われます。
Warping window sizeの概念は以下の図がわかりやすいと思います。
<img width="404" alt="スクリーンショット 2020-02-15 午後2 25 38" src="https://user-images.githubusercontent.com/47652262/74593977-26892b80-4fff-11ea-9d33-51baa2298a0c.png">
[Dynamic Time Warping Algorithm](http://www.mathcs.emory.edu/~lxiong/cs730_s13/share/slides/searching_sigkdd2012_DTW.pdf)
<img width="477" alt="スクリーンショット 2020-02-15 午後2 26 07" src="https://user-images.githubusercontent.com/47652262/74593979-29841c00-4fff-11ea-8d0e-e6ef73c57884.png">
[Time Series (2)](http://www-db.deis.unibo.it/courses/SI-M/slides/04.5.TimeSeries2.pdf)

以前ご紹介いただいた解析例ではWarping window sizeを0に設定されていたので、
その影響ではないかと思います。

次バージョンではもう少し短期間のスケッチがしやすくなる予定ですので、
またアップロードしたらご報告したいと思います。

**Comment by makotouemura** [comment]
情報、ありがとうございます。理解しました。warping window size を調整したりして、再度、挙動を見てみます。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
上記のコメントについて訂正があります。
warping windowのサイズですが、0に指定した場合は内部的には制約なし、として扱っておりました。失礼いたしました。
もしwarping windowサイズを0にした上でご報告いただいたような問題が生じているとすれば、何かしらの問題があると思われます。入力クエリを変えて色々試してみて、わかり次第、ご報告いたします。
warping windowサイズに小さい値(2とか5とか）を入力して、長さが大きく異なる時系列の比較を行った場合は、先のコメント通りの挙動になります。

混乱を招いてすみません。

**Comment by makotouemura** [comment]
はい、warping windowサイズを「指定なし」のときと「0」のときで挙動が同じことを確認しました。また、スケッチで時間的に長めのものを描いて、かつ、warping windowサイズを「0」にしたとき、Distance の小さな短いPeriodのサンプルが抽出されることがあるのも確認できました。これで当面、問題なさそうです。
