### ISSUE TITLE
コメント機能の改善

### ISSUE THREAD

**Issue by MistletoeNaoko** [MistletoeNaoko/TimeTubesWeb#13]
コメントとクエリの情報を関連付けて保存し、コメントからクエリを復元する

**Comment by MistletoeNaoko** [comment]
@makotouemura
3d7d1637b919acc187306272da54bfcc44511f6c
で、もろもろのバグ（PAPD関連、result querying、タブの遷移など）の修正と、コメント機能の大幅な変更を行いました。
**pullする前に、（もしお使いであれば）コメントを事前に出力されることをおすすめします。**

新しいコメント機能では、コメントとそのタイムスタンプなどの情報に加えて、クエリ自体の情報も保存します。
つまり、コメントから、クエリを復元することができます。
また、コメントのラベルの色も選択できるようになりました。
<img width="1424" alt="スクリーンショット 2020-02-18 午前0 08 32" src="https://user-images.githubusercontent.com/47652262/74705808-221d6800-51e3-11ea-850f-8e35ab8be61a.png">
新しいコメントページは上図のようになっています。
これまでの簡易なコメントのリスト表示に加え、左のテーブルから任意のコメントをクリックして選択すると右側のカラムにそのコメントやそのコメントと合わせて保存されているクエリの情報（なんのモードで検索したのか、スケッチならどんな変数をスケッチパッドや幅に割り当てていたのか、など）を見ることができます。
また、右側のカラムの上部には'RECOVER THE QUERY'と書かれた青いボタンが表示されます。
これをクリックしていただくと、クエリの状態を再現する（パラメタやスケッチなどの復元）ことができます。
（すでにお気づきかもしれませんが、左のテーブルはHeaderをクリックすることで並び替えも可能です。）
コメントの入力方法などには大きな変更はありません。

この変更に伴い、結果やクエリ、コメントなどの出力形式が変わりました。
全てjsonで出力され、コメントについては使用されたクエリの情報も出力されます。
query-by-sketchの出力も形式が変わってしまったので、**現在は以前に出力したクエリのファイルは読み込めません**（ミーティング時に出力していただいたものとか）。もしクエリの出力・読み込み機能をお使いであれば、早急に対応いたします。

以下は、既存のバージョンでコメント機能をお使いになっていた場合の注意事項です。
コメントの保存形式や構造が変わったので内部で自動で現在のフォーマットに変換していますが、
もしうまく変換できないようでしたら、以下のlocalStorageのリセットをお試しください。
過去のコメントは消えてしまうので、事前にexportしておくことをお勧めします。
1. ブラウザ上で右クリックして、`要素を調査`を押し、開発者ツールを開く（F12でも開けると思います）
2. `ストレージ`のタブを選択
3. 左のカラムから`ローカルストレージ`を選択
4. `http://localhost:8080/`をクリック
5. 右側にlocalStorageの内容が表示されるので、その中の`privateComment`の列を選択して右クリック、`"privateComment"を削除`を選択
以上の手順で`privateComment`を削除してから、アプリを再読み込みすれば、コメントの情報は消えますが問題なく動くと思います。
コメント機能を使っていない、もしくは、前のバージョンの段階でコメントを一旦全て削除していれば上記の手順でリセットする必要はありません。

**Comment by MistletoeNaoko** [comment]
@makotouemura
申し訳ありません、変換にミスがありました。
08acf4703780781066346c8f00574f86e6f19e30
こちらの最新版をpullしてください。

**Comment by makotouemura** [comment]
コメント機能、確認しました。あまり意味のある感想にならないかもしれませんが、以下、思ったことを書いておきます。
コメント機能は、検索して出てきたサンプルに対して「本物」「偽物」「微妙」みたいなコメントをつけてそれぞれ色も変えたら見やすいかな、と思ってました。実際にそのような使いやすさはありますが、Distance の閾値を下げてサンプルを増やすと（40個とか）１つ１つにコメントつけるのが面倒になりますね。その場合は特に覚えておきたい重要なものにだけコメントする、という使い方が良さそうです。

**Comment by MistletoeNaoko** [comment]
感想ありがとうございます。
微妙なのもTimeTubesのviewの方でマークが出てくると煩わしいので、本物だと思ったものにだけコメントするといいかもしれませんね…
例えば、ミーティングでのPDと光度の正の相関を実際に示しているものは赤で、負の相関を実際に示しているものには青、みたいな感じでマークしたり、みたいな使い方（検索ごとに色を変えてみる）もできるかと思います。
クエリも復元できるので、コメントを残したものについて、これなんだっけ？、と思ったらぜひお試しください。
