### ISSUE TITLE
Query-by-sketchにてResult queryingを実行時に、軸変更でスケッチを変形する

### ISSUE THREAD

**Issue by MistletoeNaoko** [MistletoeNaoko/TimeTubesWeb#16]
検出結果をResult queryingでスケッチに変換した際に、その時区間の情報を保存し、
スケッチパッドのx軸やy軸、幅に割り当てた変数を変更した際に自動でスケッチ自体も更新する。
（変数変更時に結果一覧からスケッチパッド上にドラッグし直さなくてよいようにする）

**Comment by MistletoeNaoko** [comment]
@makotouemura
5b266606c24aeb8cf4dd0abc6936882ec17583ab
で対応しました。
最新版ではお使いいただけます。

スケッチを変形したり、新しいスケッチを描くまでは情報が保持されます。
（i.e. Result queryingで時区間をスケッチに変形した後に、制御点を足したり、変形したりすると情報が失われます。）

**Comment by makotouemura** [comment]
なるほど。動作確認しました。
