### ISSUE TITLE
Visual Query Sketch の run

### ISSUE THREAD

**Issue by makotouemura** [MistletoeNaoko/TimeTubesWeb#6]
Visual Query の sketch で、スケッチして各種パラメータを設定した後で run のボタンを押しても何も結果が出ないことがあります。これが、1) 検索したが条件を満たす結果がゼロ件だった、2) 検索中で結果が出るまでに時間がかかる、3) 何かしらの問題があってそもそも検索されていない、の、どの状態なのかがわからないので、わかるような表示が欲しいです。

**Comment by MistletoeNaoko** [comment]
ご指摘ありがとうございます。
検索中に'searching...'、検索後にヒットした件数'(件数) results are found'を表示するようにしました。
バグで検索が止まったりした場合の表示は現段階では実装できていません。もし何か問題があった場合は、プロセスを示すテキストが'searching'からヒットした件数にいつまでたっても移行しない、という状態になると思います。おかしいな、と思われた場合は、ブラウザの開発者ツール（f12を押すかWebページ上を右クリックして「検証」や「要素を調査」などをクリック）を開き、タブからコンソールを開いていただくと、何かしらのエラーが表示されていると思います。
私がテストしている範囲ではまだ検索がうまくいかない、というようなバグには遭遇していませんが、もし何か問題が生じましたら、使用したデータセットの内容とfeature extractionのモードやパラメタ、コンソールに表示されたバグの内容をissueに投げていただけると助かります。
よろしくお願いします。
