### ISSUE TITLE
feature extraction から visualization(TimeTubes)へ戻るとTubeが表示されない

### ISSUE THREAD

**Issue by makotouemura** [MistletoeNaoko/TimeTubesWeb#7]
Feature extraction で、例えば visual query sketch をして run して出てきた候補をクリックして visualization に戻ろうとすると、TimeTubes画面で Tubeが表示されず真っ黒になります。

**Comment by MistletoeNaoko** [comment]
バグの報告ありがとうございます。修正いたしましたので、最新版のmasterをpullしてください。
