### ISSUE TITLE
Visual Query 複数回検索後の数直線表示

### ISSUE THREAD

**Issue by makotouemura** [MistletoeNaoko/TimeTubesWeb#8]
Visual Query, Query-by-sketch で1回検索した後、別の sketch をして再度検索すると、結果は正常動作してそうに見えますが、一番上の、結果を数直線（時系列）上に表示するところが最初の結果のまま、更新されません。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
727375bdd05e059736ea26d33cbc993cb9c64918
にて修正いたしました。
最新版のmasterをpullしてください。
