### ISSUE TITLE
マウスホイール操作と画面内のオレンジのライン操作による時刻移動

### ISSUE THREAD

**Issue by makotouemura** [MistletoeNaoko/TimeTubesWeb#9]
マウスホイールによる時間方向の移動と、TimeTubesに常に表示されている光度曲線内のオレンジの縦棒をドラッグすることによる時間方向の移動で、挙動が異なることがあるようです。

まず、"AVERAGE"で50日くらいの平均値を設定すると赤丸が表示され、マウスホイールを動かすと赤丸も動きますが、光度曲線内のオレンジ棒を動かしたり、その下の緑丸で表示されている光度曲線内の点をダブルクリックしてその時刻に移動しても、平均を示す赤丸は変化しません。オレンジ棒を動かすと細かい変動が追えないので通常マウスホイールを多用してますが、数十日の平均の変化を見るにはマウスホイールだとゆっくりすぎるので、オレンジ棒を動かしたくなります。マウスホイールで動かせる速度が変えられても良いかもしれません。

次に、光度曲線を拡大するため、灰色部分の端をドラッグして描画範囲を狭めた時、マウスホイールの操作によって移動する tube と、光度曲線のなかで動いているオレンジ棒の時刻が少しずれることがあります。マウスホイールを動かして時刻を変えると、現在時刻の点が TimeTubesは赤く強調されますが、緑丸の光度曲線ではオレンジに縁取りされて強調されます。これらは一致してます。縦のオレンジ棒の移動だけがズレているようです。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
ご報告ありがとうございます。バグを取りきれていなくて本当に申し訳ございません。
>Averageを表示している時にオレンジの棒を動かしてもaverageの位置が更新されない

727375bdd05e059736ea26d33cbc993cb9c64918
にて修正いたしました。

>散布図をbrushingした際に現在時刻を示す線位置が補間時に少しずれる

9104386317f63af28b5a27e73ff99b69b683bdbc
にて修正いたしました。

マウスホイールの感度の変更も近日中に対応したいと思います。
対応いたしましたら、またこちらでご報告させていただきます。

**Comment by MistletoeNaoko** [comment]
@makotouemura 
04dd9a2a7063042af37ee1569656cee765af4d4c
にて、マウスホイールの感度の変更が可能になりました。
ファイル入力の横の歯車を押すと、ドロップダウンメニューが表示されます。
そこから、マウス感度を4種類から選んでいただけます。
マウス感度の設定に関わらず、全ての観測点を通るようになっています。

また何かわからないことなどありましたらいつでもご連絡ください。
